CREATE TYPE "public"."availability_status" AS ENUM('available', 'busy', 'away', 'offline');--> statement-breakpoint
CREATE TYPE "public"."building_type" AS ENUM('low_rise', 'mid_rise', 'high_rise', 'detached', 'semi_detached', 'terraced', 'cluster');--> statement-breakpoint
CREATE TYPE "public"."fuel_type" AS ENUM('gasoline', 'diesel', 'electric', 'hybrid', 'lpg', 'cng');--> statement-breakpoint
CREATE TYPE "public"."furnishing" AS ENUM('unfurnished', 'partially_furnished', 'fully_furnished', 'luxury_furnished');--> statement-breakpoint
CREATE TYPE "public"."listing_category" AS ENUM('accommodation', 'real_estate', 'transportation', 'tours', 'activities', 'dining', 'shopping', 'services', 'events', 'vehicles', 'products');--> statement-breakpoint
CREATE TYPE "public"."listing_purpose" AS ENUM('rent', 'sale', 'short_term_rental', 'long_term_rental', 'both');--> statement-breakpoint
CREATE TYPE "public"."listing_status" AS ENUM('draft', 'active', 'inactive', 'sold', 'rented', 'reserved', 'maintenance', 'pending_approval', 'rejected', 'expired');--> statement-breakpoint
CREATE TYPE "public"."listing_type" AS ENUM('accommodation', 'service', 'vehicle', 'product');--> statement-breakpoint
CREATE TYPE "public"."orientation" AS ENUM('north', 'south', 'east', 'west', 'northeast', 'northwest', 'southeast', 'southwest');--> statement-breakpoint
CREATE TYPE "public"."price_type" AS ENUM('fixed', 'negotiable', 'auction', 'quote_on_request');--> statement-breakpoint
CREATE TYPE "public"."product_condition" AS ENUM('new', 'like_new', 'excellent', 'good', 'fair', 'poor', 'for_parts');--> statement-breakpoint
CREATE TYPE "public"."product_listing_type" AS ENUM('sale', 'rent', 'both', 'service');--> statement-breakpoint
CREATE TYPE "public"."product_status" AS ENUM('active', 'inactive', 'sold', 'rented', 'reserved', 'maintenance', 'draft', 'pending_approval', 'rejected');--> statement-breakpoint
CREATE TYPE "public"."product_type" AS ENUM('vehicle', 'electronics', 'furniture', 'clothing', 'sports', 'tools', 'books', 'home_garden', 'jewelry', 'toys', 'health_beauty', 'food_beverage', 'real_estate', 'services', 'other');--> statement-breakpoint
CREATE TYPE "public"."property_status" AS ENUM('available', 'rented', 'sold', 'reserved', 'under_contract', 'off_market', 'maintenance');--> statement-breakpoint
CREATE TYPE "public"."property_type" AS ENUM('condo', 'apartment', 'house', 'villa', 'townhouse', 'studio', 'penthouse', 'duplex', 'loft', 'commercial', 'office', 'retail', 'warehouse', 'land', 'building');--> statement-breakpoint
CREATE TYPE "public"."provider_type" AS ENUM('individual', 'company', 'agency', 'freelancer');--> statement-breakpoint
CREATE TYPE "public"."transmission_type" AS ENUM('manual', 'automatic', 'cvt', 'semi_automatic');--> statement-breakpoint
CREATE TYPE "public"."vehicle_category" AS ENUM('economy', 'standard', 'premium', 'luxury', 'sport', 'electric', 'classic');--> statement-breakpoint
CREATE TYPE "public"."vehicle_condition" AS ENUM('new', 'excellent', 'good', 'fair', 'poor');--> statement-breakpoint
CREATE TYPE "public"."vehicle_status" AS ENUM('available', 'rented', 'maintenance', 'reserved', 'inactive');--> statement-breakpoint
CREATE TYPE "public"."vehicle_type" AS ENUM('scooter', 'motorcycle', 'car', 'bicycle', 'truck', 'van', 'bus', 'boat', 'jet_ski', 'atv', 'other');--> statement-breakpoint
CREATE TYPE "public"."verification_level" AS ENUM('basic', 'verified', 'premium', 'enterprise');--> statement-breakpoint
CREATE TYPE "public"."view_type" AS ENUM('city', 'sea', 'mountain', 'garden', 'pool', 'river', 'park', 'golf', 'no_view');--> statement-breakpoint
CREATE TABLE "listing_availability" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"listing_id" uuid NOT NULL,
	"start_date" timestamp NOT NULL,
	"end_date" timestamp NOT NULL,
	"is_available" boolean DEFAULT true NOT NULL,
	"price" numeric(10, 2),
	"notes" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "listing_bookings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"listing_id" uuid NOT NULL,
	"customer_id" uuid NOT NULL,
	"start_date" timestamp NOT NULL,
	"end_date" timestamp NOT NULL,
	"total_price" numeric(12, 2) NOT NULL,
	"status" varchar(20) DEFAULT 'pending' NOT NULL,
	"payment_status" varchar(20) DEFAULT 'pending' NOT NULL,
	"special_requests" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "listings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"owner_id" uuid NOT NULL,
	"title" varchar(200) NOT NULL,
	"description" text NOT NULL,
	"category" "listing_category" NOT NULL,
	"type" "listing_type" NOT NULL,
	"status" "listing_status" DEFAULT 'draft' NOT NULL,
	"base_price" numeric(12, 2) NOT NULL,
	"currency" varchar(3) DEFAULT 'THB' NOT NULL,
	"location_address" text NOT NULL,
	"location_city" varchar(100) NOT NULL,
	"location_region" varchar(100) NOT NULL,
	"location_country" varchar(100) DEFAULT 'Thailand' NOT NULL,
	"location_zip_code" varchar(20),
	"location_latitude" numeric(10, 8),
	"location_longitude" numeric(11, 8),
	"images" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"main_image" varchar(500),
	"videos" jsonb DEFAULT '[]'::jsonb,
	"tags" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"keywords" jsonb DEFAULT '[]'::jsonb,
	"slug" varchar(250),
	"is_verified" boolean DEFAULT false NOT NULL,
	"verification_date" timestamp,
	"quality_score" numeric(3, 2),
	"trust_score" numeric(3, 2),
	"views" integer DEFAULT 0 NOT NULL,
	"favorites" integer DEFAULT 0 NOT NULL,
	"inquiries" integer DEFAULT 0 NOT NULL,
	"average_rating" numeric(3, 2) DEFAULT '0',
	"review_count" integer DEFAULT 0 NOT NULL,
	"moderation_status" varchar(20) DEFAULT 'pending' NOT NULL,
	"moderation_notes" text,
	"flag_reasons" jsonb DEFAULT '[]'::jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"published_at" timestamp,
	"expires_at" timestamp,
	"metadata" jsonb DEFAULT '{}'::jsonb,
	"custom_fields" jsonb DEFAULT '{}'::jsonb
);
--> statement-breakpoint
CREATE TABLE "products" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"listing_id" uuid NOT NULL,
	"product_type" "product_type" NOT NULL,
	"subcategory" varchar(100),
	"condition" "product_condition" NOT NULL,
	"status" "product_status" DEFAULT 'active' NOT NULL,
	"listing_type" "product_listing_type" NOT NULL,
	"brand" varchar(50),
	"model" varchar(100),
	"serial_number" varchar(100),
	"manufacturing_year" integer,
	"country_of_origin" varchar(50),
	"length" integer,
	"width" integer,
	"height" integer,
	"weight" integer,
	"volume" integer,
	"material" varchar(100),
	"size" varchar(50),
	"technical_specs" jsonb DEFAULT '{}'::jsonb,
	"features" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"included" jsonb DEFAULT '[]'::jsonb,
	"requirements" jsonb DEFAULT '[]'::jsonb,
	"condition_notes" text,
	"defects" jsonb DEFAULT '[]'::jsonb,
	"repairs" jsonb DEFAULT '[]'::jsonb,
	"warranty_period" varchar(50),
	"warranty_type" varchar(20),
	"support_available" boolean DEFAULT false,
	"manual_included" boolean DEFAULT false,
	"price" numeric(12, 2) NOT NULL,
	"price_type" "price_type" NOT NULL,
	"original_price" numeric(12, 2),
	"msrp" numeric(12, 2),
	"rental_pricing" jsonb,
	"shipping_cost" numeric(8, 2),
	"handling_fee" numeric(8, 2),
	"installation_fee" numeric(8, 2),
	"accepted_payments" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"installment_available" boolean DEFAULT false,
	"installment_options" jsonb DEFAULT '[]'::jsonb,
	"is_available" boolean DEFAULT true NOT NULL,
	"quantity" integer,
	"quantity_type" varchar(20) DEFAULT 'exact',
	"stock_level" varchar(20) DEFAULT 'in_stock',
	"restock_date" timestamp,
	"available_from" timestamp,
	"available_until" timestamp,
	"blackout_dates" jsonb DEFAULT '[]'::jsonb,
	"available_locations" jsonb DEFAULT '[]'::jsonb,
	"pickup_locations" jsonb DEFAULT '[]'::jsonb,
	"delivery_available" boolean DEFAULT false,
	"delivery_areas" jsonb DEFAULT '[]'::jsonb,
	"delivery_time" varchar(50),
	"seller_id" uuid NOT NULL,
	"seller_type" varchar(20) NOT NULL,
	"seller_name" varchar(100) NOT NULL,
	"seller_rating" numeric(3, 2),
	"seller_reviews" integer DEFAULT 0,
	"is_seller_verified" boolean DEFAULT false,
	"business_license" varchar(100),
	"tax_id" varchar(50),
	"contact_phone" varchar(20),
	"contact_email" varchar(100),
	"contact_website" varchar(200),
	"contact_address" text,
	"social_media" jsonb DEFAULT '{}'::jsonb,
	"business_hours" varchar(100),
	"languages" jsonb DEFAULT '[]'::jsonb,
	"response_time" varchar(50),
	"return_policy" text,
	"warranty_policy" text,
	"shipping_policy" text,
	"documents" jsonb DEFAULT '[]'::jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"metadata" jsonb DEFAULT '{}'::jsonb,
	"custom_fields" jsonb DEFAULT '{}'::jsonb
);
--> statement-breakpoint
CREATE TABLE "property_amenities" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"real_estate_id" uuid NOT NULL,
	"has_elevator" boolean DEFAULT false,
	"has_swimming_pool" boolean DEFAULT false,
	"has_fitness_center" boolean DEFAULT false,
	"has_sauna" boolean DEFAULT false,
	"has_garden" boolean DEFAULT false,
	"has_playground" boolean DEFAULT false,
	"has_security" boolean DEFAULT false,
	"has_cctv" boolean DEFAULT false,
	"has_key_card" boolean DEFAULT false,
	"has_reception" boolean DEFAULT false,
	"has_concierge" boolean DEFAULT false,
	"has_mailbox" boolean DEFAULT false,
	"has_air_conditioning" boolean DEFAULT false,
	"has_heating" boolean DEFAULT false,
	"has_washing_machine" boolean DEFAULT false,
	"has_dryer" boolean DEFAULT false,
	"has_dishwasher" boolean DEFAULT false,
	"has_microwave" boolean DEFAULT false,
	"has_refrigerator" boolean DEFAULT false,
	"has_oven" boolean DEFAULT false,
	"has_balcony" boolean DEFAULT false,
	"has_terrace" boolean DEFAULT false,
	"has_fireplace" boolean DEFAULT false,
	"has_storage" boolean DEFAULT false,
	"has_wifi" boolean DEFAULT false,
	"has_cable_tv" boolean DEFAULT false,
	"has_smart_tv" boolean DEFAULT false,
	"has_intercom" boolean DEFAULT false,
	"has_smart_home" boolean DEFAULT false,
	"is_wheelchair_accessible" boolean DEFAULT false,
	"has_handicap_parking" boolean DEFAULT false,
	"pets_allowed" boolean DEFAULT false,
	"cats_allowed" boolean DEFAULT false,
	"dogs_allowed" boolean DEFAULT false,
	"pet_deposit" numeric(8, 2),
	"custom_amenities" jsonb DEFAULT '[]'::jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "property_rules" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"real_estate_id" uuid NOT NULL,
	"check_in_time" varchar(10),
	"check_out_time" varchar(10),
	"self_check_in" boolean DEFAULT false,
	"keypad_entry" boolean DEFAULT false,
	"max_guests" integer,
	"infants_allowed" boolean DEFAULT true,
	"children_allowed" boolean DEFAULT true,
	"events_allowed" boolean DEFAULT false,
	"parties_allowed" boolean DEFAULT false,
	"smoking_allowed" boolean DEFAULT false,
	"quiet_hours_start" varchar(10),
	"quiet_hours_end" varchar(10),
	"cancellation_policy" varchar(20) DEFAULT 'moderate',
	"house_rules" text,
	"additional_rules" jsonb DEFAULT '[]'::jsonb,
	"has_smoke_detector" boolean DEFAULT false,
	"has_carbon_monoxide_detector" boolean DEFAULT false,
	"has_fire_extinguisher" boolean DEFAULT false,
	"has_first_aid_kit" boolean DEFAULT false,
	"has_security_camera" boolean DEFAULT false,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "real_estate" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"listing_id" uuid NOT NULL,
	"property_type" "property_type" NOT NULL,
	"property_status" "property_status" DEFAULT 'available' NOT NULL,
	"listing_purpose" "listing_purpose" NOT NULL,
	"bedrooms" integer NOT NULL,
	"bathrooms" numeric(3, 1) NOT NULL,
	"area" numeric(8, 2) NOT NULL,
	"living_area" numeric(8, 2),
	"land_area" numeric(10, 2),
	"floor" integer,
	"total_floors" integer,
	"building_type" "building_type",
	"building_age" integer,
	"year_built" integer,
	"year_renovated" integer,
	"furnishing" "furnishing" DEFAULT 'unfurnished' NOT NULL,
	"condition" varchar(20) DEFAULT 'good' NOT NULL,
	"views" jsonb DEFAULT '[]'::jsonb,
	"orientation" "orientation",
	"balconies" integer DEFAULT 0,
	"terraces" integer DEFAULT 0,
	"price" numeric(12, 2) NOT NULL,
	"price_per_sqm" numeric(8, 2),
	"currency" varchar(3) DEFAULT 'THB' NOT NULL,
	"price_type" "price_type" DEFAULT 'fixed' NOT NULL,
	"daily_rate" numeric(8, 2),
	"weekly_rate" numeric(8, 2),
	"monthly_rate" numeric(8, 2),
	"yearly_rate" numeric(10, 2),
	"maintenance_fee" numeric(8, 2),
	"common_area_fee" numeric(8, 2),
	"security_deposit" numeric(10, 2),
	"cleaning_fee" numeric(6, 2),
	"electricity_included" boolean DEFAULT false,
	"water_included" boolean DEFAULT false,
	"internet_included" boolean DEFAULT false,
	"cable_included" boolean DEFAULT false,
	"gas_included" boolean DEFAULT false,
	"parking_spaces" integer DEFAULT 0,
	"parking_type" varchar(20),
	"parking_fee" numeric(6, 2),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"metadata" jsonb DEFAULT '{}'::jsonb
);
--> statement-breakpoint
CREATE TABLE "service_providers" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar(255) NOT NULL,
	"provider_type" "provider_type" NOT NULL,
	"business_name" varchar(100),
	"display_name" varchar(50) NOT NULL,
	"bio" text NOT NULL,
	"avatar" varchar(500),
	"cover_image" varchar(500),
	"email" varchar(255) NOT NULL,
	"phone" varchar(50) NOT NULL,
	"website" varchar(500),
	"social_media" jsonb,
	"primary_location" jsonb NOT NULL,
	"service_areas" jsonb,
	"verification_level" "verification_level" DEFAULT 'basic',
	"is_verified" boolean DEFAULT false,
	"availability_status" "availability_status" DEFAULT 'available',
	"business_licenses" jsonb,
	"certifications" jsonb,
	"service_capabilities" jsonb,
	"languages" jsonb DEFAULT '[]'::jsonb,
	"settings" jsonb,
	"total_bookings" integer DEFAULT 0,
	"completed_bookings" integer DEFAULT 0,
	"average_rating" numeric(3, 2) DEFAULT '0.00',
	"total_reviews" integer DEFAULT 0,
	"response_time_minutes" integer,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"verified_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "vehicles" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"listing_id" uuid NOT NULL,
	"vehicle_type" "vehicle_type" NOT NULL,
	"category" "vehicle_category" NOT NULL,
	"condition" "vehicle_condition" NOT NULL,
	"status" "vehicle_status" DEFAULT 'available' NOT NULL,
	"make" varchar(50) NOT NULL,
	"model" varchar(100) NOT NULL,
	"year" integer NOT NULL,
	"color" varchar(30) NOT NULL,
	"engine_size" varchar(20),
	"power" varchar(20),
	"max_speed" integer,
	"fuel_consumption" numeric(5, 2),
	"fuel_type" "fuel_type" NOT NULL,
	"transmission" "transmission_type" NOT NULL,
	"seating_capacity" integer NOT NULL,
	"doors" integer,
	"length" integer,
	"width" integer,
	"height" integer,
	"weight" integer,
	"features" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"safety_features" jsonb DEFAULT '[]'::jsonb,
	"comfort_features" jsonb DEFAULT '[]'::jsonb,
	"technology_features" jsonb DEFAULT '[]'::jsonb,
	"license_plate" varchar(20) NOT NULL,
	"registration_number" varchar(50),
	"engine_number" varchar(50),
	"chassis_number" varchar(50),
	"insurance_number" varchar(50),
	"insurance_expiry" timestamp,
	"tech_inspection_expiry" timestamp,
	"documents_complete" boolean DEFAULT false NOT NULL,
	"documents_verified" boolean DEFAULT false NOT NULL,
	"documents_notes" text,
	"hourly_rate" numeric(8, 2),
	"daily_rate" numeric(8, 2),
	"weekly_rate" numeric(8, 2),
	"monthly_rate" numeric(8, 2),
	"yearly_rate" numeric(8, 2),
	"security_deposit" numeric(10, 2) NOT NULL,
	"insurance_per_day" numeric(8, 2),
	"delivery_fee" numeric(8, 2),
	"pickup_fee" numeric(8, 2),
	"late_fee" numeric(8, 2),
	"damage_fee" numeric(8, 2),
	"fuel_policy" varchar(20) DEFAULT 'full_to_full' NOT NULL,
	"fuel_cost_per_liter" numeric(5, 2),
	"duration_discounts" jsonb DEFAULT '{}'::jsonb,
	"current_location" text NOT NULL,
	"pickup_locations" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"delivery_available" boolean DEFAULT false NOT NULL,
	"delivery_radius" integer,
	"service_areas" jsonb DEFAULT '[]'::jsonb,
	"restricted_areas" jsonb DEFAULT '[]'::jsonb,
	"is_available" boolean DEFAULT true NOT NULL,
	"available_from" timestamp,
	"available_until" timestamp,
	"blackout_dates" jsonb DEFAULT '[]'::jsonb,
	"total_rentals" integer DEFAULT 0 NOT NULL,
	"total_kilometers" integer DEFAULT 0 NOT NULL,
	"last_service_date" timestamp,
	"last_service_km" integer,
	"next_service_due" timestamp,
	"next_service_km" integer,
	"maintenance_notes" text,
	"gps_tracker_id" varchar(50),
	"gps_provider" varchar(50),
	"has_charger" boolean DEFAULT false,
	"has_helmet" boolean DEFAULT false,
	"has_lock" boolean DEFAULT false,
	"accessories" jsonb DEFAULT '[]'::jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"last_maintenance_update" timestamp,
	"metadata" jsonb DEFAULT '{}'::jsonb,
	"notes" text
);
--> statement-breakpoint
ALTER TABLE "listing_availability" ADD CONSTRAINT "listing_availability_listing_id_listings_id_fk" FOREIGN KEY ("listing_id") REFERENCES "public"."listings"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "listing_bookings" ADD CONSTRAINT "listing_bookings_listing_id_listings_id_fk" FOREIGN KEY ("listing_id") REFERENCES "public"."listings"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "products" ADD CONSTRAINT "products_listing_id_listings_id_fk" FOREIGN KEY ("listing_id") REFERENCES "public"."listings"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "property_amenities" ADD CONSTRAINT "property_amenities_real_estate_id_real_estate_id_fk" FOREIGN KEY ("real_estate_id") REFERENCES "public"."real_estate"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "property_rules" ADD CONSTRAINT "property_rules_real_estate_id_real_estate_id_fk" FOREIGN KEY ("real_estate_id") REFERENCES "public"."real_estate"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "real_estate" ADD CONSTRAINT "real_estate_listing_id_listings_id_fk" FOREIGN KEY ("listing_id") REFERENCES "public"."listings"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vehicles" ADD CONSTRAINT "vehicles_listing_id_listings_id_fk" FOREIGN KEY ("listing_id") REFERENCES "public"."listings"("id") ON DELETE cascade ON UPDATE no action;